export const ADD_LOCAL_TRACK = 'ADD_LOCAL_TRACK';
export const UPDATE_LOCAL_TRACK = 'UPDATE_LOCAL_TRACK';
export const REMOVE_LOCAL_TRACK = 'REMOVE_LOCAL_TRACK';
export const LOCAL_TRACK_ACTION = 'LOCAL_TRACK_ACTION';

export const ADD_REMOTE_TRACK  = 'ADD_REMOTE_TRACK';
export const UPDATE_REMOTE_TRACK  = 'UPDATE_REMOTE_TRACK';
export const REMOVE_REMOTE_TRACK  = 'REMOVE_REMOTE_TRACK';
export const REMOTE_TRACK_ACTION = 'REMOTE_TRACK_ACTION';

export const ADD_CONFERENCE = 'ADD_CONFERENCE';
export const ADD_CONNECTION = 'ADD_CONNECTION'
export const CONNECTION_ACTION = 'CONNECTION_ACTION';
export const CONFERENCE_ACTION = 'CONFERENCE_ACTION';

export const ADD_TRACK = "addTrack";
export const REMOVE_TRACK = "removeTrack";
export const REPLACE_TRACK  = "replaceTrack";

export const CREATE_LOCAL_TRACKS = "CREATE_LOCAL_TRACKS";
export const INIT_SDK =